//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAddressBookService")]
    public interface IAddressBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetAllAddresses", ReplyAction="http://tempuri.org/IAddressBookService/GetAllAddressesResponse")]
        AddressBook.Common.Models.AddressBookModel[] GetAllAddresses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/GetAllAddresses", ReplyAction="http://tempuri.org/IAddressBookService/GetAllAddressesResponse")]
        System.Threading.Tasks.Task<AddressBook.Common.Models.AddressBookModel[]> GetAllAddressesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/AddAddress", ReplyAction="http://tempuri.org/IAddressBookService/AddAddressResponse")]
        void AddAddress(AddressBook.Common.Models.AddressBookModel addressBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressBookService/AddAddress", ReplyAction="http://tempuri.org/IAddressBookService/AddAddressResponse")]
        System.Threading.Tasks.Task AddAddressAsync(AddressBook.Common.Models.AddressBookModel addressBook);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressBookServiceChannel : AddressBook.ServiceReference1.IAddressBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressBookServiceClient : System.ServiceModel.ClientBase<AddressBook.ServiceReference1.IAddressBookService>, AddressBook.ServiceReference1.IAddressBookService {
        
        public AddressBookServiceClient() {
        }
        
        public AddressBookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressBookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressBookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AddressBook.Common.Models.AddressBookModel[] GetAllAddresses() {
            return base.Channel.GetAllAddresses();
        }
        
        public System.Threading.Tasks.Task<AddressBook.Common.Models.AddressBookModel[]> GetAllAddressesAsync() {
            return base.Channel.GetAllAddressesAsync();
        }
        
        public void AddAddress(AddressBook.Common.Models.AddressBookModel addressBook) {
            base.Channel.AddAddress(addressBook);
        }
        
        public System.Threading.Tasks.Task AddAddressAsync(AddressBook.Common.Models.AddressBookModel addressBook) {
            return base.Channel.AddAddressAsync(addressBook);
        }
    }
}
