//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_book
    {
        public long id { get; set; }
        public string name { get; set; }
        public long contact { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public bool in_the_country { get; set; }
    }
}
